[project]
name = "qumlib"
version = "0.1.1"
description = "A minimal quantum computing simulation library"
authors = [{ name="Chaitanya" }]
dependencies = ["numpy"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
